---
dist: xenial

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.7.*
  - ANSIBLE_VERSION=2.6.*
  - ANSIBLE_VERSION=2.5.*

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi
  - ansible-galaxy install znerol.gpg_export
  - ansible-galaxy install znerol.wkd

script:
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local
