---
dist: xenial

language: python
python:
  - "3.5"
  - "3.6"

cache: pip

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.7.*
  - ANSIBLE_VERSION=2.6.*
  - ANSIBLE_VERSION=2.5.*

stages:
  - lint
  - test

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - ansible-galaxy install znerol.gpg_export
  - ansible-galaxy install znerol.wkd
script:
  - ansible-playbook -i tests/inventory tests/test.yml --connection=local

jobs:
  include:
    - stage: lint
      python: "3.6"
      env:
        - ANSIBLE_VERSION=latest
      install:
        - pip install ansible-lint
      script:
        - ansible-lint .

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
