---
- vars:
    _wkd_method: "{{ wkd_method | default('advanced') }}"
    _wkd_gpg_key_directory: "{{ wkd_basedir }}/{{ wkd_gpg_uid | wkd_dir(wkd_method=_wkd_method) }}"
    _wkd_gpg_export_params: "{{ wkd_gpg_export_params | default({}) | combine(_wkd_gpg_export_params_defaults) }}"
    _wkd_gpg_export_params_defaults:
        armor: False
        mode: exact_email

  block:
    - name: WKD directory present
      check_mode: no
      changed_when: no
      loop: "{{ wkd_gpg_uids | list }}"
      loop_control:
        loop_var: wkd_gpg_uid
      file:
        state: directory
        path: "{{ _wkd_gpg_key_directory }}"
        recurse: true

    - name: GPG key exported
      loop: "{{ wkd_gpg_uids | list }}"
      loop_control:
        loop_var: wkd_gpg_uid
      copy:
        content: "{{ lookup('gpg_export', wkd_gpg_uid, **_wkd_gpg_export_params) }}"
        dest: "{{ _wkd_gpg_key_directory }}/{{ wkd_gpg_uid | wkd_hash() }}"
