---
- vars:
    wkd_method: "{{ wkd_method | default('advanced') }}"
    wkd_gpg_key_directory: "{{ wkd_basedir }}/{{ wkd_gpg_uid | wkd_dir(wkd_method=wkd_method) }}"
  block:
    - name: WKD directory present
      check_mode: no
      changed_when: no
      loop: "{{ wkd_gpg_uids | list }}"
      loop_control:
        loop_var: wkd_gpg_uid
      file:
        state: directory
        path: "{{ wkd_gpg_key_directory }}"
        recurse: true

    - name: GPG key exported
      check_mode: no
      changed_when: no
      loop: "{{ wkd_gpg_uids | list }}"
      loop_control:
        loop_var: wkd_gpg_uid
      include_tasks: wkd_key.yml
